services:
  db:
    image: postgres:17-alpine
    container_name: smart-invoice-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:11.7.2
    container_name: smart-invoice-flyway
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-invoice_db}
      FLYWAY_USER: ${POSTGRES_USER:-invoice_user}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-invoice_pass}
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql
    command: -baselineOnMigrate=true migrate

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: smart-invoice-backend
    depends_on:
      flyway:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-invoice_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-invoice_user}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-invoice_pass}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: