spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/invoice_db}
    username: ${SPRING_DATASOURCE_USERNAME:-invoice_user}
    password: ${SPRING_DATASOURCE_PASSWORD:-invoice_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
